format = """
$username\
$hostname\
$directory\
$fill\
$git_metrics\
$git_status\
$git_commit\
$git_branch\
$time\
$line_break\
$character"""

add_newline = true

[character]
success_symbol = '[❯](purple)'
error_symbol = '[❯](red)'

[directory]
style = 'bold #019A66'
truncate_to_repo = true
truncation_length = 3
truncation_symbol = '…/'

[fill]
symbol = " "

[git_branch]
symbol = ''
format = '[$symbol$branch]($style) '
style = 'bright-black'

[git_commit]
commit_hash_length = 7
only_detached = false
format = '[$hash$tag]($style) '
style = '#811199'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'cyan'

[git_metrics]
disabled = false
format = '([+$added]($added_style))([-$deleted]($deleted_style) )'
added_style = 'green'
deleted_style = 'red'

[hostname]
ssh_only = false
format = '[@$hostname](#4D4DAB):'

[time]
disabled = false
format = '[$time]($style)'
style = 'yellow'

[username]
style_user = '#4D4DAB'
style_root = 'bold red'
format = '[$user]($style)'
show_always = true


