format = """
$username\
$hostname\
$directory\
$fill\
$git_metrics\
$git_status\
$git_commit\
$git_branch\
$time\
$line_break\
$character"""

add_newline = true

[character]
success_symbol = '[❯](#35a770)'
error_symbol = '[❯](#bd0f2f)'

[directory]
style = '#1f5872'
truncate_to_repo = true
truncation_length = 5
truncation_symbol = '…/'

[fill]
symbol = " "

[git_branch]
symbol = ''
format = '[$symbol$branch]($style) '
style = '#404a55'

[git_commit]
commit_hash_length = 7
only_detached = false
format = '[$hash$tag]($style) '
style = '#2a8bc1'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = '#a0b6d3'

[git_metrics]
disabled = false
format = '([+$added]($added_style))([-$deleted]($deleted_style) )'
added_style = '#35a770'
deleted_style = '#bd0f2f'

[hostname]
ssh_only = true
format = '[@$hostname](#4D4DAB):'

[time]
disabled = false
format = '[$time]($style)'
style = '#fb9435'

[username]
style_user = '#4D4DAB'
style_root = 'bold #bd0f2f'
format = '[$user]($style)'
show_always = false

